package:
  name: "artifician"
  version: "0.4.8"
about:
  home: "https://github.com/Plato-solutions/artifician"
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: "Artifician is an event driven library developed to simplify the process of preparation of the dataset for Artificial Intelligence models."
source:
  path: ..
build:
  noarch: python
  number: 1
channel_targets:
  - conda-forge main
test:
  imports:
    - artifician
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - rx>=3.2.0
    - pandas>=1.4.2
    - beautifulsoup4
