package:
  name: "artifician"
  version: "0.1.5"
about:
  home: "https://github.com/Plato-solutions/artifician"
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: "Artifician is an event driven framework developed to simplify the process of preparation of the dataset for Artificial Intelligence models."
source:
  path: ..
build:
  number: 6
test:
  imports:
    - artifician
requirements:
  host:
    - python
    - pip
  run:
    - python
    - rx
    - pandas
